# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Rubem Nakamura"
description: > # this means to ignore newlines until "email:"
   Blog

email: rubem.nakamura@gmail.com
#blog logo
logo: "/assets/images/rubemnakamura.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Rubem Nakamura'
author: 'Rubem Nakamura'
author_image: "/assets/images/rubemnakamura.jpg"

paginate:	5

url: "http://rubemnakamura.com.br"
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/rubemz
    desc: Follow me on twitter
    share_url: https://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/rubemz
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
